// Maps Wikidata team names (current, historical, relocated, renamed) to the
// current franchise abbreviation the game uses. Legacy franchises collapse
// into their modern team, per the spec (Seattle SuperSonics -> OKC, etc.).
export const TEAM_NAME_TO_ABBR: Record<string, string> = {
  // Current 30
  'Atlanta Hawks': 'ATL',
  'Boston Celtics': 'BOS',
  'Brooklyn Nets': 'BKN',
  'Charlotte Hornets': 'CHA',
  'Chicago Bulls': 'CHI',
  'Cleveland Cavaliers': 'CLE',
  'Dallas Mavericks': 'DAL',
  'Denver Nuggets': 'DEN',
  'Detroit Pistons': 'DET',
  'Golden State Warriors': 'GSW',
  'Houston Rockets': 'HOU',
  'Indiana Pacers': 'IND',
  'Los Angeles Clippers': 'LAC',
  'LA Clippers': 'LAC',
  'Los Angeles Lakers': 'LAL',
  'Memphis Grizzlies': 'MEM',
  'Miami Heat': 'MIA',
  'Milwaukee Bucks': 'MIL',
  'Minnesota Timberwolves': 'MIN',
  'New Orleans Pelicans': 'NOP',
  'New York Knicks': 'NYK',
  'Oklahoma City Thunder': 'OKC',
  'Orlando Magic': 'ORL',
  'Philadelphia 76ers': 'PHI',
  'Phoenix Suns': 'PHX',
  'Portland Trail Blazers': 'POR',
  'Sacramento Kings': 'SAC',
  'San Antonio Spurs': 'SAS',
  'Toronto Raptors': 'TOR',
  'Utah Jazz': 'UTA',
  'Washington Wizards': 'WAS',

  // Relocated / renamed -> modern franchise
  'Seattle SuperSonics': 'OKC',
  'New Jersey Nets': 'BKN',
  'New York Nets': 'BKN',
  'Vancouver Grizzlies': 'MEM',
  'Washington Bullets': 'WAS',
  'Capital Bullets': 'WAS',
  'Baltimore Bullets': 'WAS',
  'Chicago Packers': 'WAS',
  'Chicago Zephyrs': 'WAS',
  'San Diego Clippers': 'LAC',
  'Buffalo Braves': 'LAC',
  'Kansas City Kings': 'SAC',
  'Kansas City-Omaha Kings': 'SAC',
  'Cincinnati Royals': 'SAC',
  'Rochester Royals': 'SAC',
  'New Orleans Jazz': 'UTA',
  'Charlotte Bobcats': 'CHA',
  'New Orleans Hornets': 'NOP',
  'New Orleans/Oklahoma City Hornets': 'NOP',
  'San Diego Rockets': 'HOU',
  'Fort Wayne Pistons': 'DET',
  'Minneapolis Lakers': 'LAL',
  'Philadelphia Warriors': 'GSW',
  'San Francisco Warriors': 'GSW',
  'St. Louis Hawks': 'ATL',
  'Milwaukee Hawks': 'ATL',
  'Tri-Cities Blackhawks': 'ATL',
  'Syracuse Nationals': 'PHI',
}

export function teamToAbbr(name: string): string | null {
  return TEAM_NAME_TO_ABBR[name.trim()] ?? null
}
